const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');

const {
  installExampleSkill,
  createInstalledSkillMissingEntrypointFixture,
  createFakeCodexCommand,
} = require('./helpers/skill-test-helpers');
const {
  syncInstalledSkillToCodex,
  generateCodexSkillFromInstalledSkill,
} = require('../src/chat/codex-skill-adapter');

test('exports syncInstalledSkillToCodex as public API alias', async () => {
  assert.equal(syncInstalledSkillToCodex, generateCodexSkillFromInstalledSkill);
});

test('createFakeCodexCommand creates a node script with binPath metadata', async () => {
  const fake = await createFakeCodexCommand();
  const script = await fs.readFile(fake.commandPath, 'utf8');

  assert.equal(fake.binPath, fake.commandPath);
  if (process.platform !== 'win32') {
    assert.match(script, /^#!\/usr\/bin\/env node/);
  }
  assert.match(script, /fake codex started/);
});

test('generates a Codex skill directory from an installed skill', async () => {
  const { installedSkill } = await installExampleSkill();
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));

  const result = await syncInstalledSkillToCodex(installedSkill, {
    codexSkillsRoot,
  });

  const targetDir = path.join(codexSkillsRoot, installedSkill.id);
  const skillMd = await fs.readFile(path.join(targetDir, 'SKILL.md'), 'utf8');
  const copiedSystem = await fs.readFile(path.join(targetDir, 'references', 'system.md'), 'utf8');
  const sourceSystem = await fs.readFile(path.join(installedSkill.installedPath, 'system.md'), 'utf8');
  const copiedSchema = JSON.parse(
    await fs.readFile(path.join(targetDir, 'references', 'inputs.schema.json'), 'utf8')
  );
  const sourceSchema = JSON.parse(
    await fs.readFile(path.join(installedSkill.installedPath, 'inputs.schema.json'), 'utf8')
  );
  const provenance = JSON.parse(
    await fs.readFile(path.join(targetDir, 'references', 'book-to-skill.json'), 'utf8')
  );

  assert.equal(result.codexSkillPath, targetDir);
  assert.match(skillMd, /^---\nname: pyramid-writing-skill\n/);
  assert.match(skillMd, /description:/);
  assert.match(skillMd, /references\/system\.md/);
  assert.match(skillMd, /references\/inputs\.schema\.json/);
  assert.match(skillMd, /avoid reproducing copyrighted source text/i);
  assert.equal(copiedSystem, sourceSystem);
  assert.deepEqual(copiedSchema, sourceSchema);
  assert.equal(provenance.generated_by, 'book-to-skill');
  assert.equal(provenance.source_skill.id, installedSkill.id);
  assert.equal(provenance.source_skill.installed_path, installedSkill.installedPath);
});

test('refuses to overwrite existing non book-to-skill Codex skill content', async () => {
  const { installedSkill } = await installExampleSkill();
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));
  const targetDir = path.join(codexSkillsRoot, installedSkill.id);

  await fs.mkdir(targetDir, { recursive: true });
  await fs.writeFile(path.join(targetDir, 'SKILL.md'), '# user-authored\n', 'utf8');

  await assert.rejects(
    () =>
      generateCodexSkillFromInstalledSkill(installedSkill, {
        codexSkillsRoot,
      }),
    /Refusing to overwrite existing Codex skill directory/i
  );
});

test('overwrites an existing Codex skill generated by book-to-skill', async () => {
  const { installedSkill } = await installExampleSkill();
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));
  const targetDir = path.join(codexSkillsRoot, installedSkill.id);

  await generateCodexSkillFromInstalledSkill(installedSkill, { codexSkillsRoot });
  await fs.writeFile(path.join(installedSkill.installedPath, 'system.md'), '# refreshed\n', 'utf8');

  await generateCodexSkillFromInstalledSkill(installedSkill, { codexSkillsRoot });

  const skillMd = await fs.readFile(path.join(targetDir, 'SKILL.md'), 'utf8');
  const copiedSystem = await fs.readFile(path.join(targetDir, 'references', 'system.md'), 'utf8');
  assert.match(skillMd, /name: pyramid-writing-skill/);
  assert.equal(copiedSystem, '# refreshed\n');
});

test('fails with clear error when configured system prompt file is missing', async () => {
  const { installedSkill } = await createInstalledSkillMissingEntrypointFixture({
    file: 'system.md',
  });
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));

  await assert.rejects(
    () => generateCodexSkillFromInstalledSkill(installedSkill, { codexSkillsRoot }),
    /missing configured skill file.*system\.md/i
  );
});

test('fails with clear error when configured inputs schema file is missing', async () => {
  const { installedSkill } = await createInstalledSkillMissingEntrypointFixture({
    file: 'inputs.schema.json',
  });
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));

  await assert.rejects(
    () => generateCodexSkillFromInstalledSkill(installedSkill, { codexSkillsRoot }),
    /missing configured skill file.*inputs\.schema\.json/i
  );
});

test('rejects manifest id that escapes codex skills root', async () => {
  const { installedSkill } = await installExampleSkill();
  const manifestPath = path.join(installedSkill.installedPath, 'skill.json');
  const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
  manifest.id = '../escape-target';
  await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));

  await assert.rejects(
    () => generateCodexSkillFromInstalledSkill(installedSkill, { codexSkillsRoot }),
    /invalid manifest id|escapes codex root/i
  );
});

test('rejects system prompt entrypoint path that escapes installed package root', async () => {
  const { installedSkill } = await installExampleSkill();
  const manifestPath = path.join(installedSkill.installedPath, 'skill.json');
  const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
  manifest.entrypoints.system_prompt_file = '../outside-system.md';
  await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));

  await assert.rejects(
    () => generateCodexSkillFromInstalledSkill(installedSkill, { codexSkillsRoot }),
    /escapes package root.*system_prompt_file/i
  );
});

test('rejects inputs schema entrypoint path that escapes installed package root', async () => {
  const { installedSkill } = await installExampleSkill();
  const manifestPath = path.join(installedSkill.installedPath, 'skill.json');
  const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
  manifest.entrypoints.inputs_schema_file = '../outside-inputs.schema.json';
  await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  const codexSkillsRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'bts-codex-root-'));

  await assert.rejects(
    () => generateCodexSkillFromInstalledSkill(installedSkill, { codexSkillsRoot }),
    /escapes package root.*inputs_schema_file/i
  );
});
